server:
    port: 8000
spring:
    main:
         # 启用懒加载初始化模式，Spring beans 在实际需要时才被初始化，而不是在应用启动时全部初始化。
        lazy-initialization: true
    application:
        name: "jpa-demo"
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/jpa-demo?useUnicode=true&rewriteBatchedStatements=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password:
    jpa:
        # 关闭 Open Entity Manager in View 模式，避免事务处理上的问题。
        open-in-view: false
        # 打印 SQL 语句到日志，便于调试。
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    # JDBC 批处理大小，提升批量操作性能。
                    batch_size: 10
                    # 优化插入顺序，减少索引更新次数。
                    order_inserts: true
                    # 优化更新顺序
                    order_updates: true
                # 格式化打印的 SQL，增加可读性。
                format_sql: true
                # 设置 Hibernate 的方言为 MySQL 5
                dialect: org.hibernate.dialect.MySQL5Dialect
    flyway:
        #是否启用
        enabled: true
        # 可以支持多个location, 用','隔开
        locations: classpath:db/migration
        #是否创建元数据表
        validate-on-migrate: true
        # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
        clean-disabled: true
        # 如果数据库不是空表，需要设置成 true，否则启动报错
        baseline-on-migrate: true
        # 版本控制日志表，默认flyway_schema_history,不同系统建议修改数据
        # table: flyway_schema_history
    graphql:
        graphiql:
             enabled: true